### ISSUE TITLE
Modelo - API para que el usuario ingresa sus datos históricos

### ISSUE THREAD

**Issue by cecigolazo** [merlin-cba/ISPC-ciencia-de-datos-2023#18]
Analizamos si hacemos una función para consumir una API, Formulario de Google u otro, para que el usuario ingrese su históricos

**Comment by merlin-cba** [comment]
debemos implementar los 2 (dos) métodos desde el menú de opciones
1 - Entrenar nuevo modelo (cargar nuevo set de datos)
2 - Entrenar modelo con datos Actualizados (Actualizar datos) --> Re entrenar
3 - Ingresar nueva predicción  --> ingresar fecha a predecir
