### ISSUE TITLE
Primer reunión de equipo

### ISSUE THREAD

**Issue by Emmanuel-Reynoso** [merlin-cba/ISPC-ciencia-de-datos-2023#4]
### WEB

1. - Cargar la WIKI para saber como interactuar con Flask.
2. - Armar el diseño (Ema, Vivi y Ceci)
3. - Armar la estructura esperada (Que menus y que van a hacer)
4. - Interacción esperada del usuario (Si es un formulario, si quiere re-entrenar el modelo)
5. - Integrar la base en GitHub (Ema)

### Modelo

1. Pasar de Notebook a .py (Oscar)
2. Dejamos el modelo entrenado (pkl)
3. Crear la función para tomar los datos del usuario, para que entrene el modelo con sus propios datos.
4. Evaluar si hacemos una función para consumir una API, Formulario de Google u otro, para que el usuario ingrese su históricos.
5. Test error, precisión, R*R - (Opcional)

### Infraestructura

1. Evaluar servidor en el que vamos a colgar la web. Heroku, AWS, Netlify, GitHub Page u Oscar 
2. Evaluar el CI / CD. GitHub Actions u otros
3. Cada cuanto se va a reentrenar el modelo. (Opcional)

### Organización

1. Configurar el repositorio para que todos podamos ordenar el SCRUM
2. Armar un esquema general en el área de Wiki
3. Cargar el primer Sprint

**Comment by Emmanuel-Reynoso** [comment]
### WEB

1. - Cargar la WIKI para saber como interactuar con Flask.
2. - Armar el diseño (Ema, Vivi y Ceci)
3. - Armar la estructura esperada (Que menus y que van a hacer)
4. - Interacción esperada del usuario (Si es un formulario, si quiere re-entrenar el modelo)
5. - Integrar la base en GitHub (Ema)

### Modelo

1. Pasar de Notebook a .py (Oscar)
2. Dejamos el modelo entrenado (pkl)
3. Crear la función para tomar los datos del usuario, para que entrene el modelo con sus propios datos.
4. Evaluar si hacemos una función para consumir una API, Formulario de Google u otro, para que el usuario ingrese su históricos.
5. Test error, precisión, R*R - (Opcional)

### Infraestructura

1. Evaluar servidor en el que vamos a colgar la web. Heroku, AWS, Netlify, GitHub Page u Oscar 
2. Evaluar el CI / CD. GitHub Actions u otros
3. Cada cuanto se va a reentrenar el modelo. (Opcional)

**Comment by Emmanuel-Reynoso** [comment]
Debemos pasar esto al Backlog y asignar las tareas.

**Comment by cecigolazo** [comment]
Ok, mañana inicio la carga.

**Comment by merlin-cba** [comment]
sprint cerrado
